apiVersion: v1
entries:
  alertmanager-webhook-adapter:
    - apiVersion: v2
      appVersion: 1.1.8
      created: "2024-09-24T19:49:08.071811+08:00"
      description: helm chart for alertmanager webhook adapter
      digest: bbf9f592581bf32ec72a28c648db37792ae05cd6420a382490546338cc84d015
      maintainers:
        - name: bougou
      name: alertmanager-webhook-adapter
      type: application
      urls:
        - oci://registry-1.docker.io/bougoucharts/alertmanager-webhook-adapter:v1.0.0
      version: v1.0.0
  kube-prometheus-stack:
    - annotations:
        artifacthub.io/license: Apache-2.0
        artifacthub.io/links: |
          - name: Chart Source
            url: https://github.com/prometheus-community/helm-charts
          - name: Upstream Project
            url: https://github.com/prometheus-operator/kube-prometheus
        artifacthub.io/operator: "true"
      apiVersion: v2
      appVersion: v0.76.1
      created: "2024-09-24T19:49:08.091944+08:00"
      dependencies:
        - condition: crds.enabled
          name: crds
          repository: ""
          version: 0.0.0
        - condition: kubeStateMetrics.enabled
          name: kube-state-metrics
          repository: https://prometheus-community.github.io/helm-charts
          version: 5.25.*
        - condition: nodeExporter.enabled
          name: prometheus-node-exporter
          repository: https://prometheus-community.github.io/helm-charts
          version: 4.39.*
        - condition: grafana.enabled
          name: grafana
          repository: https://grafana.github.io/helm-charts
          version: 8.5.*
        - condition: windowsMonitoring.enabled
          name: prometheus-windows-exporter
          repository: https://prometheus-community.github.io/helm-charts
          version: 0.6.*
      description: kube-prometheus-stack collects Kubernetes manifests, Grafana dashboards, and Prometheus rules combined with documentation and scripts to provide easy to operate end-to-end Kubernetes cluster monitoring with Prometheus using the Prometheus Operator.
      digest: cfba7d08b4ac55093e02a897d33ded8215b6574d9656dbcf2bfb9fc246494fdd
      home: https://github.com/prometheus-operator/kube-prometheus
      icon: https://raw.githubusercontent.com/prometheus/prometheus.github.io/master/assets/prometheus_logo-cb55bb5c346.png
      keywords:
        - operator
        - prometheus
        - kube-prometheus
      kubeVersion: '>=1.19.0-0'
      maintainers:
        - email: andrew@quadcorps.co.uk
          name: andrewgkew
        - email: gianrubio@gmail.com
          name: gianrubio
        - email: github.gkarthiks@gmail.com
          name: gkarthiks
        - email: kube-prometheus-stack@sisti.pt
          name: GMartinez-Sisti
        - email: github@jkroepke.de
          name: jkroepke
        - email: scott@r6by.com
          name: scottrigby
        - email: miroslav.hadzhiev@gmail.com
          name: Xtigyro
        - email: quentin.bisson@gmail.com
          name: QuentinBisson
      name: kube-prometheus-stack
      sources:
        - https://github.com/prometheus-community/helm-charts
        - https://github.com/prometheus-operator/kube-prometheus
      type: application
      urls:
        - oci://registry-1.docker.io/bougoucharts/kube-prometheus-stack:v62.7.0
      version: v62.7.0
generated: "2024-09-24T19:49:08.07131+08:00"
